### ISSUE TITLE
Wrong value for BASE_FOLDER in structure.py

### ISSUE THREAD

**Issue by didirus** [ykerus/obsidian-templates#1]
Running `make structure` gives me the following error:

```> make structure
python .obsidian/scripts/structure.py
make: python: No such file or directory
make: *** [structure] Error 1
```

Running `structure.py` directly gives me a more detailed error:

```> python .obsidian/scripts/structure.py
Traceback (most recent call last):
  File ".obsidian/scripts/structure.py", line 100, in <module>
    structure_daily_notes(
  File ".obsidian/scripts/structure.py", line 81, in structure_daily_notes
    for daily_note in os.listdir(daily_notes_folder):
FileNotFoundError: [Errno 2] No such file or directory: '00. 📓 Log/🗒 Daily'
```

Changing line 5 to 
`BASE_FOLDER = "📓 Log"` 

should do the trick

**Comment by ykerus** [comment]
Fixed in [b7c635463e503a718b093753637941c2bd4c3241](https://github.com/ykerus/obsidian-templates/commit/b7c635463e503a718b093753637941c2bd4c3241)
